sudo: required
language: python
services:
  - docker

env:
  global:
    - IMAGE_USER=praekeltfoundation
    - REGISTRY_USER=praekeltorgdeploy
    - secure: "RRvCtuewG7fmh/5p8KL4KUskXQySW0Z21KdELU319aTvY842CqHtr/K9Kq3J6rvx7cltcJv2xM+/4L/Oed0Ow4h76VcoPSXNXYNx537RvWwMaylR28sWqFz1dU99RJbZvoO00IlH8v7Lok8REysYYpgvW6oHEYJ4tak6sTJQQyKtd1rr74q2KCpmN1hwb2VUdihNzCLmwd6VNBiLibZA6S1Sn2w4CCCXq0vMeT5CZMW0vt5I7Kel4EZ4bLEE2P2Fk8QK1LrqLPeFBt6gfThn+EimWXqddzQAgtoBp7u80XsKsSYPe5UIYtnP2/Ax9E33RvIALpt62YMgAVF0B5qOmz3LqRcFQRu6ht/88OL6mBPzDkpT2kHkY01zIzNWx6BHFT+qZ0CjHrewCss/hMrKa8qkdcrOE3WT/ISlRHYPOMnt8/Pw3qZxTqMtrPCQfZqVZ9U0S+0dcQdOiIwcxGS2TNqc5OmX28WE3/zQ0gJ6L6SnVzt2B+dc4RY+xbbWQVk5GTTtL5WaNDAyOxQfsbEH/BgqUz0pRsbazrqDI3gzZe7B3I7iaVzYjRx9mQh8dpc8Gg19xyOoFulf1kqErhGAF3Vshf52hl6B8dsDH4mNIUHEeZWTODVz4h8M5oYJ6OhVy+yGNdf3OFO+BILPTLUXF+tcQvp+xDtLnM7+rIhGmvg="

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" -y docker-engine

before_script:
  - image="$IMAGE_USER/alpine-buildpack-deps"

script:
  - docker build -t "$image:curl" curl
  - docker build -t "$image:scm" scm
  - docker build -t "$image:slim" slim
  - docker build -t "$image" .

after_script:
  - docker images

before_deploy:
  - images="$(docker images --format '{{.Repository}}:{{.Tag}}' | grep "$image" | tr "\n" " ")"
  - pip install docker-ci-deploy
deploy:
  provider: script
  script: ./deploy.sh $images
  on:
    branch: develop
