sudo: required
language: python
services:
  - docker

branches:
  only: [master]

env:
  global:
    - REGISTRY_USER=praekeltorgdeploy
    - secure: "RRvCtuewG7fmh/5p8KL4KUskXQySW0Z21KdELU319aTvY842CqHtr/K9Kq3J6rvx7cltcJv2xM+/4L/Oed0Ow4h76VcoPSXNXYNx537RvWwMaylR28sWqFz1dU99RJbZvoO00IlH8v7Lok8REysYYpgvW6oHEYJ4tak6sTJQQyKtd1rr74q2KCpmN1hwb2VUdihNzCLmwd6VNBiLibZA6S1Sn2w4CCCXq0vMeT5CZMW0vt5I7Kel4EZ4bLEE2P2Fk8QK1LrqLPeFBt6gfThn+EimWXqddzQAgtoBp7u80XsKsSYPe5UIYtnP2/Ax9E33RvIALpt62YMgAVF0B5qOmz3LqRcFQRu6ht/88OL6mBPzDkpT2kHkY01zIzNWx6BHFT+qZ0CjHrewCss/hMrKa8qkdcrOE3WT/ISlRHYPOMnt8/Pw3qZxTqMtrPCQfZqVZ9U0S+0dcQdOiIwcxGS2TNqc5OmX28WE3/zQ0gJ6L6SnVzt2B+dc4RY+xbbWQVk5GTTtL5WaNDAyOxQfsbEH/BgqUz0pRsbazrqDI3gzZe7B3I7iaVzYjRx9mQh8dpc8Gg19xyOoFulf1kqErhGAF3Vshf52hl6B8dsDH4mNIUHEeZWTODVz4h8M5oYJ6OhVy+yGNdf3OFO+BILPTLUXF+tcQvp+xDtLnM7+rIhGmvg="
  matrix:
    - VERSION=3.5 TAG_LATEST=
    - VERSION=3.6 TAG_LATEST=
    - VERSION=3.7 TAG_LATEST=1

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - image="$(awk '$1 == "FROM" { print $2; exit }' "$VERSION"/Dockerfile | cut -d':' -f1):$VERSION"
  # Pull full image to use as cache
  - docker pull "$image" || true

script:
  - docker build --pull --cache-from "$image" -t "$image"-curl "$VERSION"/curl
  - docker build --cache-from "$image" -t "$image"-scm "$VERSION"/scm
  - docker build --cache-from "$image" -t "$image"-slim "$VERSION"/slim
  - docker build --cache-from "$image" -t "$image" "$VERSION"
  # Run the tests for the official Docker images. There are no tests specific to
  # buildpack-deps so just let the scripts run the default tests.
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

before_deploy:
  - images="$(docker images --format '{{.Repository}}:{{.Tag}}' | grep "$image" | tr "\n" " ")"
  - pip install docker-ci-deploy==0.3.0
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: dcd --version "$VERSION" ${TAG_LATEST:+--version-latest} $images
  on:
    branch: master
