dist: xenial
language: python
services: docker

branches:
  only: [master]

env:
  global:
    - REGISTRY_USER=praekeltorgdeploy
    - secure: "RRvCtuewG7fmh/5p8KL4KUskXQySW0Z21KdELU319aTvY842CqHtr/K9Kq3J6rvx7cltcJv2xM+/4L/Oed0Ow4h76VcoPSXNXYNx537RvWwMaylR28sWqFz1dU99RJbZvoO00IlH8v7Lok8REysYYpgvW6oHEYJ4tak6sTJQQyKtd1rr74q2KCpmN1hwb2VUdihNzCLmwd6VNBiLibZA6S1Sn2w4CCCXq0vMeT5CZMW0vt5I7Kel4EZ4bLEE2P2Fk8QK1LrqLPeFBt6gfThn+EimWXqddzQAgtoBp7u80XsKsSYPe5UIYtnP2/Ax9E33RvIALpt62YMgAVF0B5qOmz3LqRcFQRu6ht/88OL6mBPzDkpT2kHkY01zIzNWx6BHFT+qZ0CjHrewCss/hMrKa8qkdcrOE3WT/ISlRHYPOMnt8/Pw3qZxTqMtrPCQfZqVZ9U0S+0dcQdOiIwcxGS2TNqc5OmX28WE3/zQ0gJ6L6SnVzt2B+dc4RY+xbbWQVk5GTTtL5WaNDAyOxQfsbEH/BgqUz0pRsbazrqDI3gzZe7B3I7iaVzYjRx9mQh8dpc8Gg19xyOoFulf1kqErhGAF3Vshf52hl6B8dsDH4mNIUHEeZWTODVz4h8M5oYJ6OhVy+yGNdf3OFO+BILPTLUXF+tcQvp+xDtLnM7+rIhGmvg="
  matrix:
    - VERSION=3.8 TAG_LATEST=
    - VERSION=3.9 TAG_LATEST=1

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - image="$(awk '$1 == "FROM" { print $2; exit }' "$VERSION"/Dockerfile | cut -d':' -f1):$VERSION"
  # Pull full image to use as cache
  - docker pull "$image" || true

script:
  - docker build --pull --cache-from "$image" -t "$image"-curl "$VERSION"/curl
  - docker build --cache-from "$image" -t "$image"-scm "$VERSION"/scm
  - docker build --cache-from "$image" -t "$image"-slim "$VERSION"/slim
  - docker build --cache-from "$image" -t "$image" "$VERSION"
  # Run the tests for the official Docker images. There are no tests specific to
  # buildpack-deps so just let the scripts run the default tests.
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

before_deploy:
  - images="$(docker images --format '{{.Repository}}:{{.Tag}}' | grep "$image" | tr "\n" " ")"
  - pip install docker-ci-deploy==0.3.0
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
deploy:
  provider: script
  script: dcd --version "$VERSION" ${TAG_LATEST:+--version-latest} $images
  on:
    branch: master

notifications:
  slack:
    rooms:
      # praekeltfoundation:<token>#docker
      - secure: "UJLv5HKnlLA1wbB2pUSoEskHIoB6iIh8zmIrUMwzXgN0PMifYKc+DS2KdfNWuQG7YjBSo1EizI3n329wNaRuVx6IvQB8uWPXkzOF4Fp6Y0icKlB5f/3VUAn9ZNoO6fB234CNDgWXPS0fYPuPPSfkzkANjWD4j0lA0EAkaKrHwY3r7rLaPKGbF410kmaIYocKP+y/KG8E1K4JKWPq7uXJorSjPseIRtMeeWZpeKFDnkaPNT4f1PuDwc0UjpAa3koebiSTGNH2dHGcfyRXzq3h9JyfTKuM94hPTc798iVzSGwc20M7Qbu9juyv+z+5nxzzz1qjxsWZbLERAByaQPLRhoZ2vPAgDg9s/lC96VC39xWS31wNE7MytA62+odhqpWbcE6Ko5lSOCQGkwReCiE2OX17j5pXQtHexnOIdIrJx2NPRUY5jD6LDXwghDjEykDhxSuFsX+lDcW78x5y6VECv6OmPVtk74WXbUTP3iaf0h9z+xZDfKs1lMb9DWVHq6cyrXEn21S73YZ14TDGJC2sL77I+TGYXGsPJBD/H2JwxW++DpjjMl0iuqNopRrXOIJf0KwXRbRROALDptmSfvz77V7V14s3WDLo5NttRRjRuss9siM2zbsU7175AfBthOrojLBNAAY0cQq2sJLVsq8zVFlD/lWCsBxQ919sV7dDFSk="
    on_pull_requests: false
